import type { Metadata } from "next";
import { Playfair_Display, Spline_Sans, Inter } from "next/font/google";
import "quill/dist/quill.snow.css";
import { Toaster } from "react-hot-toast";
import { getPublicSettingsService } from "./services/settingService";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
});

const splineSans = Spline_Sans({
  subsets: ["latin"],
  variable: "--font-spline",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});


type PublicSettingsResponse = {
  siteName?: string | null;
  favicon?: string | null;
};

async function getPublicSettings(): Promise<{
  title: string;
  favicon: string;
  description: string;
}> {
  const fallbackTitle = "Flexi Capital";
  const fallbackFavicon = "/favicon.ico";
  const fallbackDescription = "Generated by create next app";

  try {
    const res = await getPublicSettingsService();
    const setting: PublicSettingsResponse = res?.data || {};
    const title = setting.siteName?.trim() || fallbackTitle;
    const favicon = setting.favicon
      ? `${setting.favicon}${setting.favicon.includes("?") ? "&" : "?"}v=${Date.now()}`
      : fallbackFavicon;

    return {
      title,
      favicon,
      description: fallbackDescription,
    };
  } catch (error) {
    console.log("Public settings fetch error:", error);
    return {
      title: fallbackTitle,
      favicon: fallbackFavicon,
      description: fallbackDescription,
    };
  }
}
export async function generateMetadata(): Promise<Metadata> {
  const { title, favicon, description } = await getPublicSettings();

  return {
    title,
    description,
    icons: {
      icon: favicon,
      shortcut: favicon,
      apple: favicon,
    },
  };
}
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${playfair.variable} ${splineSans.variable} ${inter.variable} antialiased`}
      >
        {children}
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
