import type { Metadata } from "next";
import { Playfair_Display, Spline_Sans, Inter } from "next/font/google";
import 'quill/dist/quill.snow.css';
import { Toaster } from "react-hot-toast";
import { getPublicSettingsService } from "./services/settingService"

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
});

const splineSans = Spline_Sans({
  subsets: ["latin"],
  variable: "--font-spline",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

// ✅ DYNAMIC METADATA
export async function generateMetadata(): Promise<Metadata> {
  try {
    const res = await getPublicSettingsService();
    const setting = res?.data;

    const favicon = setting?.favicon;
    console.log("FAVICON", favicon)
    return {
      title: "Flexi Capital",
      description: "Generated by create next app",
      icons: {
        icon: favicon ? [{ url: favicon }] : [{ url: "/favicon.ico" }],
        shortcut: favicon || "/favicon.ico",
        apple: favicon || "/favicon.ico",
      },
    };
  } catch (error) {
    return {
      title: "Flexi Capital",
      description: "Generated by create next app",
      icons: {
        icon: "/favicon.ico",
      },
    };
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${splineSans.variable} ${inter.variable} antialiased`}
      >
        {children}
        <Toaster position="top-right" reverseOrder={false} />
      </body>

    </html>
  );
}
