name: Next.js CI/CD
 
on:
  push:
    branches:
      - rohit
  pull_request:
 
jobs:
  build-and-test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          cache: npm
      - name: Configure npm registry
        run: npm config set registry https://registry.npmjs.org/
 
      # - name: Install Dependencies
      #   run: npm install
 
      # - name: Run Tests
      #   run: npm test
 
      # - name: Build Next.js App
      #   run: npm run build
 
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          cache: npm
 
      - name: Install Dependencies
        run: npm install --force
 
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
 
      - name: Build App
        run: npm run build
 
      - name: Deploy to Netlify
        run: netlify deploy --build --prod --auth "nfp_vswG4LUjDxukc5qkhuT1RTTYUkHXziGg9faf" --site e0586bdb-1573-499c-9985-e6c2b8d7dec8